# Generated by Django 2.2.4 on 2019-11-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_userprofile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_location', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.CharField(blank=True, max_length=10, null=True)),
                ('event_time', models.CharField(blank=True, max_length=10, null=True)),
                ('event_time_type', models.CharField(blank=True, max_length=10, null=True)),
                ('event_time_zone', models.CharField(blank=True, max_length=10, null=True)),
                ('event_description', models.CharField(blank=True, max_length=255, null=True)),
                ('event_invitation', models.ManyToManyField(blank=True, related_name='event_invitation', to='accounts.UserProfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
