# Generated by Django 2.2.4 on 2019-11-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_time',
            field=models.TimeField(blank=True, max_length=10, null=True),
        ),
    ]
