# Generated by Django 2.2.4 on 2019-10-18 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmplyementHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile_place1', models.TextField(blank=True, null=True)),
                ('period1', models.TextField(blank=True, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('titile_place2', models.TextField(blank=True, null=True)),
                ('period2', models.TextField(blank=True, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('titile_place3', models.TextField(blank=True, null=True)),
                ('period3', models.TextField(blank=True, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
