# Generated by Django 2.2.4 on 2019-10-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emplyementhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emplyementhistory',
            old_name='description1',
            new_name='edescription1',
        ),
        migrations.RenameField(
            model_name='emplyementhistory',
            old_name='description2',
            new_name='edescription2',
        ),
        migrations.RenameField(
            model_name='emplyementhistory',
            old_name='description3',
            new_name='edescription3',
        ),
        migrations.RenameField(
            model_name='emplyementhistory',
            old_name='period1',
            new_name='eperiod1',
        ),
        migrations.RenameField(
            model_name='emplyementhistory',
            old_name='period2',
            new_name='eperiod2',
        ),
        migrations.RenameField(
            model_name='emplyementhistory',
            old_name='period3',
            new_name='eperiod3',
        ),
        migrations.RenameField(
            model_name='emplyementhistory',
            old_name='titile_place1',
            new_name='etitile_place1',
        ),
        migrations.RenameField(
            model_name='emplyementhistory',
            old_name='titile_place2',
            new_name='etitile_place2',
        ),
        migrations.RenameField(
            model_name='emplyementhistory',
            old_name='titile_place3',
            new_name='etitile_place3',
        ),
    ]
