# Generated by Django 2.2.4 on 2019-10-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191023_1536'),
        ('olympus', '0002_auto_20191024_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='accounts.UserProfile'),
        ),
    ]
