# Generated by Django 2.2.4 on 2019-10-25 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympus', '0004_auto_20191024_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
