# Generated by Django 2.2.4 on 2019-10-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympus', '0005_auto_20191025_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='liked_cr_date',
            new_name='cr_date',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='liked_post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='liked_by',
            new_name='user',
        ),
    ]
