# Generated by Django 2.2.4 on 2019-10-26 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympus', '0010_auto_20191026_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='user',
            new_name='comment_by',
        ),
        migrations.RenameField(
            model_name='usercomment',
            old_name='post',
            new_name='comment_post',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
