# Generated by Django 2.2.4 on 2019-10-26 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympus', '0011_auto_20191026_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
