# Generated by Django 2.2.4 on 2019-10-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympus', '0018_remove_usercomment_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='comment_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
