# Generated by Django 2.2.4 on 2019-10-29 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympus', '0019_auto_20191029_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='cm_likes',
            field=models.ManyToManyField(blank=True, related_name='cm_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
