# Generated by Django 2.2.4 on 2019-11-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympus', '0020_auto_20191029_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='post_video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
