# Generated by Django 2.2.4 on 2019-11-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191023_1536'),
        ('olympus', '0021_userpost_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='friends', to='accounts.UserProfile'),
        ),
    ]
