# Generated by Django 2.2.4 on 2019-11-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympus', '0023_auto_20191107_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='friends',
        ),
    ]
